### ISSUE TITLE
Error: The provided SdtElement is not a content control

### ISSUE THREAD

**Issue by dgwaldo** [antonmihaylov/OpenXmlTemplates#12]
Hitting that error again, this time my template starts off with an SdtRow...  Is  there a better way to check for this? Looks like all these elements use SdtElement as the base class... Are some SdtElement not content controls?

return e is SdtBlock || e is SdtRun || e is SdtCell || e is SdtRow;

**Comment by antonmihaylov** [comment]
That makes sense actually.

According to https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.sdtelement?view=openxml-2.8.1

you have all the SdtElements listed there, except SdtRunRuby. I'm not sure what it is, but most likely another version of an StdRun.

I think it would be safe to say that checking for is SdtElement is a good idea.
