### ISSUE TITLE
Nuget Package 2.0.2 is missing libs folder

### ISSUE THREAD

**Issue by dgwaldo** [antonmihaylov/OpenXmlTemplates#19]
Updated a project to 2.0.2 today and noticed it failed. After looking in the nuget cache folder and seeing that the actual .dll was missing I cleared the version and redownloaded.  I'm guessing this is a faulty Nuget Package?

**Comment by dgwaldo** [comment]
Curious if anyone else has ran into this?

**Comment by artemtsaryov** [comment]
Yes, I downloaded the library today and came across the same issue.

**Comment by ikazrima** [comment]
Facing the same issue. Can't reference it.

**Comment by dgwaldo** [comment]
I've pulled this project in local to our codebase for now to get around it :) I'm hoping someday a new package gets published...

**Comment by ngunna** [comment]
I am having the same issue, is this still being maintained?

**Comment by antonmihaylov** [comment]
Apologies for the radio silence
Just pushed 2.0.3 as a fix
https://www.nuget.org/packages/OpenXMLTemplates/2.0.3
