### ISSUE TITLE
Repeating images

### ISSUE THREAD

**Issue by sduncan56** [antonmihaylov/OpenXmlTemplates#26]
Not sure if I'm just imagining how this should work wrong, but - I'm trying to get a list of images inserted into the document.

Here's my JSON:
`{
   "Images":[
      {
         "image":"path\\to\\image\\image1.jpg"
      },
      {
         "image":"path\\to\\image2.jpg"
      }
   ]
}`

My template:
[tst_template.docx](https://github.com/antonmihaylov/OpenXmlTemplates/files/8768705/tst_template.docx)

In the output document, I get two images, but they're both image2.jpg. Is my JSON wrong? Or does repeating image controls not work?

**Comment by antonmihaylov** [comment]
I'm assuming this is fixed after your PR
